In [1]:
import numpy as np 
import pandas as pd
import os
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
df =  pd.read_csv("/kaggle/input/fastfood-nutrition/fastfood.csv")

In [3]:
df.head()

,restaurant,item,calories,cal_fat,total_fat,sat_fat,trans_fat,cholesterol,sodium,total_carb,fiber,sugar,protein,vit_a,vit_c,calcium,salad
0,Mcdonalds,Artisan Grilled Chicken Sandwich,380,60,7,2.0,0.0,95,1110,44,3.0,11,37.0,4.0,20.0,20.0,Other
1,Mcdonalds,Single Bacon Smokehouse Burger,840,410,45,17.0,1.5,130,1580,62,2.0,18,46.0,6.0,20.0,20.0,Other
2,Mcdonalds,Double Bacon Smokehouse Burger,1130,600,67,27.0,3.0,220,1920,63,3.0,18,70.0,10.0,20.0,50.0,Other
3,Mcdonalds,Grilled Bacon Smokehouse Chicken Sandwich,750,280,31,10.0,0.5,155,1940,62,2.0,18,55.0,6.0,25.0,20.0,Other
4,Mcdonalds,Crispy Bacon Smokehouse Chicken Sandwich,920,410,45,12.0,0.5,120,1980,81,4.0,18,46.0,6.0,20.0,20.0,Other

In [53]:
x = df[["total_fat", "total_carb", "sodium"]]
y= df["calories"]

In [54]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test= train_test_split(x,y,test_size=0.3,random_state=42)

In [55]:
import numpy as np
print(np.isnan(x_train).any())
print(np.isinf(x_train).any())
print(np.isnan(y_train).any())
print(np.isinf(y_train).any())

total_fat     False
total_carb    False
sodium        False
dtype: bool
total_fat     False
total_carb    False
sodium        False
dtype: bool
False
False

In [56]:
x_train = np.nan_to_num(x_train)
y_train = np.nan_to_num(y_train)

In [57]:
from sklearn.linear_model import LinearRegression
mlr= LinearRegression()
mlr.fit(x_train,y_train)

LinearRegression()

In [58]:
print("intercept:", mlr.intercept_)
print("coefficiants:")
list(zip(x,mlr.coef_))

intercept: 15.686456431283602
coefficiants:

[('total_fat', 9.823035071470654),
 ('total_carb', 3.9926335265045396),
 ('sodium', 0.05544386660924516)]

In [59]:
y_pred = mlr.predict(x_test)
print("prediction for test set:{}".format(y_pred))

prediction for test set:[ 313.47884301  555.53604468  355.7494352   742.89850212  431.92391798
  391.40796185  576.62230509  838.89205918  440.83613509  468.61831696
  162.25369416  907.29428479  591.76997675  675.84997027  379.70523635
  764.8196686   442.69486987  718.57885753  326.0714197   304.92227013
  565.85881735  890.71871055  775.70845478  923.78287154  407.61921278
  368.45285081  393.84811829  100.60617956  364.33371502  390.25306251
  485.64905469  480.73813906  638.10210787  696.93623069   51.52281075
  582.05440494  594.04917268  707.99054575   71.43730468  488.06824438
  400.55343165  329.34600234  758.676982    300.68891978  469.20311428
  331.62664616  390.47618824  501.17671299  543.45669708  270.02034112
  603.5531825   493.2678266   571.59645095  426.70746861  615.12266553
  484.57053602 1031.81794228  326.66031663 1023.06377879  334.45354056
  405.16411694  346.63769971  595.93368664  896.5719955   283.45602307
 1071.22693774  789.63423835  572.13329851  695.3635108   321.66626903
  585.11671275  405.63807535  554.55294566  483.58671305  615.2477199
 1134.23369359  455.84116128  429.59387651  830.38343607  733.67447983
  728.7919951   430.54324121  226.15004604  348.53835688 2149.07436372
  152.35017883  931.95053463  283.54927089  313.81015595 1026.61353652
  610.48162158  215.07548816  842.23435452  204.14357576  579.85760592
  342.3942335   810.21279494  659.51294102  788.16561719  527.54905213
  320.41547018  406.42985519  606.53356216 1060.8427238   569.71073317
  421.11705994  410.69163644  566.98986525  221.36225701  554.16958336
  461.49037061  598.5104612   763.40863317  945.78982169  339.89046395
  329.8124966   176.18020168  353.91166718  211.1944175   113.926923
  240.9630291   239.47344118  320.05572634  293.26146704  674.41098382
  356.00364353  472.15048358  519.37511761  498.14958738  275.55051233
  192.02230577  708.83630272  730.70421601  555.36086871  542.60612768
  431.289723    189.88430741  795.32392219  377.34483622  383.80605709
  731.71165744  360.56083157  655.39452919  736.25872963  442.5237935
  658.58189137  635.16148988  382.67958866  730.93939646  684.8000213
  526.39077715 1438.14201672  172.51622938  448.41780815  425.39570836]

/opt/conda/lib/python3.7/site-packages/sklearn/base.py:444: UserWarning: X has feature names, but LinearRegression was fitted without feature names
  f"X has feature names, but {self.__class__.__name__} was fitted without"

In [64]:
mlr_dif = pd.DataFrame({"actual value: ":y_test,"predited value: ":y_pred})
mlr_dif.head()

   actual value:   predited value:
0             320        313.478843
1             540        555.536045
2             340        355.749435
3             710        742.898502
4             440        431.923918

In [65]:
from sklearn import metrics
meansquare = metrics.mean_squared_error(y_test, y_pred)
print("R-squared: {:.2f}".format(mlr.score(x, y) * 100))
print("Mean Squared Error: ", meansquare)

R-squared: 95.35
Mean Squared Error:  2361.2622160605333

/opt/conda/lib/python3.7/site-packages/sklearn/base.py:444: UserWarning: X has feature names, but LinearRegression was fitted without feature names
  f"X has feature names, but {self.__class__.__name__} was fitted without"